# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define the number of worker nodes
NUM_WORKERS = 2

# Define the Kubernetes version
KUBERNETES_VERSION = "2"

# Define the Vagrant box
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Master node
  config.vm.define "kubemaster-1" do |master|
  
      master.vm.provider "virtualbox" do |master|
        vb.cpus = 2
        vb.memory = 2048
    master.vm.hostname = "kubemaster-1"
    master.vm.network "private_network", ip: "192.168.56.20"
    master.vm.provision "master", type: "shell", path: "scripts/master.sh"
     
  end

  # Worker nodes
  (1..NUM_WORKERS).each do |i|
    config.vm.define "kworker#{i}" do |worker|
      worker.vm.hostname = "kworker#{i}"
      worker.vm.network "private_network", ip: "192.168.56.21"
      worker.vm.provision "worker", type: "shell", path: "scripts/worker.sh"
    end
  end
end
